### ISSUE TITLE
On some Computers show Direct messages crash mikutter.

### ISSUE THREAD

**Issue by JPRuehmann** [mikutter/mikutter#7]
Hello
I have the following Problem on my Laptop.
If I try to show Direct Messages by doubleclicking on the User in the list mikutter crashes.

mikutter --debug
```
/usr/share/mikutter/core/plugin/user_detail_view/user_detail_view.rb:277:in `profile_head': uninitialized constant Pango::Weight (NameError)
Did you mean?  Pango::WEIGHT_BOLD
        from /usr/share/mikutter/core/plugin/user_detail_view/user_detail_view.rb:49:in `show_profile'
        from /usr/share/mikutter/core/plugin/user_detail_view/user_detail_view.rb:9:in `block (2 levels) in <top (required)>'
        from /usr/lib/ruby/vendor_ruby/pluggaloid/listener.rb:21:in `call'
        from /usr/lib/ruby/vendor_ruby/pluggaloid/event.rb:95:in `block (2 levels) in call_all_listeners'
        from /usr/lib/ruby/vendor_ruby/pluggaloid/event.rb:94:in `each'
        from /usr/lib/ruby/vendor_ruby/pluggaloid/event.rb:94:in `block in call_all_listeners'
        from /usr/lib/ruby/vendor_ruby/pluggaloid/event.rb:93:in `catch'
        from /usr/lib/ruby/vendor_ruby/pluggaloid/event.rb:93:in `call_all_listeners'
        from /usr/lib/ruby/vendor_ruby/pluggaloid/event.rb:39:in `block in call'
        from /usr/lib/ruby/vendor_ruby/delayer/procedure.rb:24:in `run'
        from /usr/lib/ruby/vendor_ruby/delayer/extend.rb:58:in `run_once'
        from /usr/lib/ruby/vendor_ruby/delayer/extend.rb:30:in `run'
        from /usr/lib/ruby/vendor_ruby/delayer.rb:43:in `method_missing'
        from /usr/share/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
        from /usr/share/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
        from /usr/share/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
        from /usr/share/mikutter/mikutter.rb:68:in `boot!'
        from /usr/share/mikutter/mikutter.rb:97:in `<main>'
```
mikutter -v
`mikutter 3.6.0-develop`
How can I make it work?

**Comment by cosmo0920** [comment]
What is the version of your using pango gem?
Perhaps, this bug caused by dependent gems.
Recently, pango gem had been migrated into gobject-introspection based binding from original C extension.

**Comment by JPRuehmann** [comment]
gem list | grep "^pango"
`pango (3.1.6, 3.1.1, 3.1.0, 3.0.9, 3.0.8)`

**Comment by cosmo0920** [comment]
mikutter develop branch assumes to use pango 3.1.6.

```irb
irb> require "pango"
# => true
irb> [Pango::Version::MAJOR, Pango::Version::MINOR, Pango::Version::MICRO]
```

will return `[3, 1, 6]` ?

**Comment by JPRuehmann** [comment]
No
`irb> require "pango"`
# => true
`irb> [Pango::Version::MAJOR, Pango::Version::MINOR, Pango::Version::MICRO]`
Returns nothing.

**Comment by cosmo0920** [comment]
Umm, what `Pango::Version::STRING` returns?

**Comment by JPRuehmann** [comment]
The Same

**Comment by cosmo0920** [comment]
Umm..., it's curious.
Does only using pango 3.1.6 solve this issue?

**Comment by JPRuehmann** [comment]
I have tried
sudo -H gem uninstall pango
sudo -H gem install pango
now
gem list | grep "^pango" says only 3.1.6
killall mikutter
mikutter
But the Problem prsists.
irb still the same too.
What makes it more curious is that it works on other PC`s.

**Comment by cosmo0920** [comment]
What is the following command output?

```bash
$  pkg-config --modversion pango 
```

If this command outputs the following string, it might have to install libpango.

```log
Package pango was not found in the pkg-config search path.
Perhaps you should add the directory containing `pango.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pango' found
```

**Comment by cosmo0920** [comment]
FYI: In my environment, I got the following outputs:

```bash
% pkg-config --modversion pango
1.40.6
```

```irb
% bundle exec irb
irb(main):001:0> require "pango"
=> true
irb(main):002:0> Pango::Version::STRING
=> "1.40.6"
irb(main):003:0> 
```

**Comment by JPRuehmann** [comment]
```
pkg-config --modversion pango                                                                                                                                              
1.38.1
```
```
bundle exec irb                                                                                                                                                            
Could not locate Gemfile or .bundle/ directory
```

**Comment by cosmo0920** [comment]
Umm..., how about the following output?

```bash
$ ls /usr/local/lib/girepository-1.0/ | grep Pango
$ ls /usr/lib/girepository-1.0/ | grep Pango
```

My environment output is:

```log
% ls /usr/local/lib/girepository-1.0/ | grep Pango
CoglPango-1.0.typelib
CoglPango-2.0.typelib
Pango-1.0.typelib
PangoCairo-1.0.typelib
PangoFT2-1.0.typelib
```

**Comment by JPRuehmann** [comment]
ls /usr/local/lib/girepository-1.0/ | grep Pango
There is no directory "girepository-1.0"
ls /usr/lib/girepository-1.0/ | grep Pango
nothing

**Comment by cosmo0920** [comment]
Oh my god! :cold_sweat:

pango 3.1.6 gem should work with gir1.2-pango-1.0 like package.
Could you install gobject-introspection package for pango?
Perhaps you should install gir1.2-pango-1.0 if you still use Debian/Ubuntu flavored distributions.

**Comment by JPRuehmann** [comment]
```
sudo apt install gir1.2-pango-1.0
gir1.2-pango-1.0« ist bereits die neuste Version (1.38.1-1)
sudo apt install gobject-introspection
»gobject-introspection« ist bereits die neuste Version (1.46.0-3ubuntu1)
```

**Comment by cosmo0920** [comment]
ls /usr/lib/*-linux-gnu/girrepository-1.0/ | grep Pango
also nothing output?

**Comment by JPRuehmann** [comment]
```
Pango-1.0.typelib
PangoCairo-1.0.typelib
PangoFT2-1.0.typelib
PangoXft-1.0.typelib
```

**Comment by cosmo0920** [comment]
Umm..., it seems that gi-based pango cannot handle gobject-introspection definition file for pango.
But I have no idea to fix this issue for now. :<

**Comment by kou** [comment]
It seems that you're using old pango gem. I think that the following command doesn't output `[3, 1, 6]`:

```console
% ruby -r pango -e 'p GLib::BINDING_VERSION'
```

I think that your system has `ruby-pango` apt package.

**Comment by JPRuehmann** [comment]
[2, 2, 5]

**Comment by JPRuehmann** [comment]
I have purged ruby-pango
now it shows
`[3, 1, 6]`
But now I cannot start mikutter anymore it says
```
/var/lib/gems/2.3.0/gems/memoist-0.16.0/lib/memoist.rb:142:in `block (2 levels) in memoize': undefined local variable or method `memoized_methods' for ConfigLoader:Module (NameError)
Did you mean?  unmemoized_method
        from /var/lib/gems/2.3.0/gems/memoist-0.16.0/lib/memoist.rb:56:in `class_eval'
        from /var/lib/gems/2.3.0/gems/memoist-0.16.0/lib/memoist.rb:56:in `memoist_eval'
        from /var/lib/gems/2.3.0/gems/memoist-0.16.0/lib/memoist.rb:132:in `block in memoize'
        from /var/lib/gems/2.3.0/gems/memoist-0.16.0/lib/memoist.rb:128:in `each'
        from /var/lib/gems/2.3.0/gems/memoist-0.16.0/lib/memoist.rb:128:in `memoize'
        from /root/mikutter/core/configloader.rb:116:in `<module:ConfigLoader>'
        from /root/mikutter/core/configloader.rb:20:in `<top (required)>'
        from /root/mikutter/core/miquire.rb:98:in `require'
        from /root/mikutter/core/miquire.rb:98:in `miquire_original_require'
        from /root/mikutter/core/miquire.rb:95:in `file_or_directory_require'
        from /root/mikutter/core/miquire.rb:76:in `block in miquire'
        from /root/mikutter/core/miquire.rb:75:in `each'
        from /root/mikutter/core/miquire.rb:75:in `miquire'
        from /root/mikutter/core/miquire.rb:18:in `miquire'
        from /root/mikutter/core/service.rb:5:in `<top (required)>'
        from /root/mikutter/core/miquire.rb:98:in `require'
        from /root/mikutter/core/miquire.rb:98:in `miquire_original_require'
        from /root/mikutter/core/miquire.rb:95:in `file_or_directory_require'
        from /root/mikutter/core/miquire.rb:76:in `block in miquire'
        from /root/mikutter/core/miquire.rb:75:in `each'
        from /root/mikutter/core/miquire.rb:75:in `miquire'
        from /root/mikutter/core/miquire.rb:18:in `miquire'
        from ./mikutter.rb:40:in `<main>'
```

**Comment by cosmo0920** [comment]
This is an another issue for memoist gem.
Using topic/1051-memoist-1.16 branch or remove memoist 1.16 and installing memoist 1.15 should solve above issue.
Or you can cheery-pick https://dev.mikutter.hachune.net/projects/mikutter/repository/revisions/a40cc99a89acf115443136e60bc9d119acb3b4e1 commit into a branch which is derived from develop.

**Comment by JPRuehmann** [comment]
OK This works, Thanks.
